%% sample_AddCRS_WKT
% This is a sample script to demonstrate how to add an OGC Coordinate
% System WKT record as a variabel length record. As the name implies, 
% the record stores information about the coordinate system in 
% Well Know Text format. 
% WKT replaced GeoTIFF in newer LAS minor versions.
%
% In this example the WKT Definition of ETRS89/UTM zone 32N, EPSG:25832
% will be written as CRS information
fprintf('\nRun: sample_AddCRS_WKT\n');

%% Add required paths
addpath('../lib')
addLASLibPaths();

%% Load File to add extrabytes
mpath = mfilename('fullpath');
[path,~,~] = fileparts(mpath);
lasFilePath = fullfile(path,'sample.las');
fprintf('     Reading File: %s\n', lasFilePath);

pcloud = readLasFile(lasFilePath);

%% Add WKT definition as a Variable Length Record
fprintf('     Add CRS Variable Length Record...\n');
data = ...
['PROJCS["ETRS89 / UTM zone 32N",',...
    'GEOGCS["ETRS89",',...
        'DATUM["European_Terrestrial_Reference_System_1989",',...
            'SPHEROID["GRS 1980",6378137,298.257222101,',...
                'AUTHORITY["EPSG","7019"]],',...
            'TOWGS84[0,0,0,0,0,0,0],',...
            'AUTHORITY["EPSG","6258"]],',...
        'PRIMEM["Greenwich",0,',...
            'AUTHORITY["EPSG","8901"]],',...
        'UNIT["degree",0.0174532925199433,',...
            'AUTHORITY["EPSG","9122"]],',...
        'AUTHORITY["EPSG","4258"]],',...
    'PROJECTION["Transverse_Mercator"],',...
    'PARAMETER["latitude_of_origin",0],',...
    'PARAMETER["central_meridian",9],',...
    'PARAMETER["scale_factor",0.9996],',...
    'PARAMETER["false_easting",500000],',...
    'PARAMETER["false_northing",0],',...
    'UNIT["metre",1,',...
        'AUTHORITY["EPSG","9001"]],',...
    'AXIS["Easting",EAST],',...
    'AXIS["Northing",NORTH],',...
    'AUTHORITY["EPSG","25832"]]'];

pcloud_modified = add_OGC_Coordinate_System_WKT_Record(pcloud, data);

%% Write new cloud to modified_samples folder
targetDir = strcat(path, '\', 'modified_samples');
if ~exist(targetDir, 'dir')
    mkdir(targetDir)
end
outPath = fullfile(targetDir, 'sample_CRS_WKT.las');

% Write the new file
fprintf('     Writing File: %s\n', outPath);
writeLasFile(pcloud_modified, outPath);

% Finished. We added two extra byte values per point of data type single.
% Our Point Data Record Length has grown to 28 bytes per record (20 + 2*4)
fprintf('     Finished!\n');
